# Generated by Django 2.1.5 on 2019-02-04 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(help_text='The X coordinate on the board.')),
                ('y', models.PositiveSmallIntegerField(help_text='The Y coordinate on the board.')),
                ('value', models.PositiveSmallIntegerField(blank=True, help_text='The value the move changes the coordinate to.', null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sudoku.Game')),
                ('previous_move', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sudoku.Move')),
            ],
        ),
    ]
