version: '3'
services:
  sudoku_be:
    container_name: sudoku_be
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=sudoku_db
      - DB_PORT=5432
      - DB_USER=sudoku_be
      - DB_PASSWORD=s0_s3cr3t
      - DB_NAME=sudoku_be

  sudoku_db:
    container_name: sudoku_db
    image: postgres:10
    environment:
      - POSTGRES_DB=sudoku_be
      - POSTGRES_USER=sudoku_be
      - POSTGRES_PASSWORD=s0_s3cr3t
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .pgdata:/var/lib/postgresql/data/pgdata
